### ISSUE TITLE
Preservation of Preferences

### ISSUE THREAD

**Issue by EffortlessFury** [Jorixon/JASM#122]
Now, this is technically a 3dmigoto issue and I'm not sure how easily a change can be made upstream (given that I believe the 3dmigoto version in use here is modified closed-source? correct me if I'm wrong). However, one thing that irks me is that my mod preferences are wiped from the 3dmigoto user config when I disable the mod. Reenabling the mod means resetting all of those persisted variables back to their default state.

Would you be opposed to an (togglable) feature where the persisted variables' state is saved after the mod is disabled (or some similar approach) and reinserted into the user config when the mod is reenabled? I have ideas for how to do this and might be able to find the time to implement it myself, but I wanted to run the idea by you first.

**Comment by Jorixon** [comment]
Hi
I don't bundle 3Dmigoto in this app and it needs to be downloaded from their GitHub. Then you tell the app where the 3dmigoto folder is located.

I tried to implement this a few months back. What I found out was that 3dmigoto seems to only save your preferences when pressing F10 and I believe it saves it to the auto generated "d3dx_user.ini" file in 3dmigoto root folder. However, I encountered some oddities with the file that I didn't understand at the time, so I decided to look more at this later.  Thinking of diving a bit deeper into how it works when I decide to start working for support for modList presets

Also, if I were to implement this, I'd like to have a better understanding of how 3dmigoto stores preferences, rather than relying solely on assumptions based on the .ini file. I'm no modder and I feel like I need to better understand 3dmigoto a bit better before I decide to tackle this. 

From the top of my head a solution based on my assumptions could be:

1. The user presses F10 to save their prefrences or we somehow trigger it when they disable a mod
2. Find the mod setting in "d3dx_user.ini"
3. Save it somewhere probably appdata
4. Then when they enable the mod again, append the line back into "d3dx_user.ini"
5. Trigger F10 (And assume that 3dmigot does not override the file...)

Anyway, I might be overthinking this or completely misunderstanding, but I would like to get his implemented at some point :)

**Comment by Jorixon** [comment]
Firstly, very nice write up I really appreciate your insight and you've given me some food for thought :)

I suddenly feel like doing some testing to confirm some things and check some of your ideas. You've made me more optimistic towards this

Also a side note
I spoke with a mod developer about making `.JASM_ModConfig.json` less personal, so that mod developers can export their mod with the file if they want. JASM currently handles existing `JASM_ModConfig.json` files fine. I haven't been able to decide if I want this to be the case or if i want a dedicated export option/feature. 

So when I mentioned appdata I was thinking about the os appdata. Then creating a mapping file that maps modId to mod settings. But this is really, a totally different issue/change altogether.

**Comment by EffortlessFury** [comment]
No prob! Depending on how the next couple of months go I may or may not be able to help with the feature, but I'd like to, at least. Also, rereading my message has me catching a few flaws (like not needing to handle something I thought JASM needed to handle lol). But I do think the whole thing can be figured out.
